<autodoc>:0: WARNING: duplicate object description of django_site.utils.AttrDict, other instance in T:\hgwork\site\docs\autodoc\django_site.rst, use :noindex: for one of them
<autodoc>:0: WARNING: duplicate object description of django_site.utils.AttrDict.define, other instance in T:\hgwork\site\docs\autodoc\django_site.rst, use :noindex: for one of them
<autodoc>:0: WARNING: duplicate object description of django_site.utils.AttrDict.resolve, other instance in T:\hgwork\site\docs\autodoc\django_site.rst, use :noindex: for one of them
<autodoc>:0: WARNING: duplicate object description of django_site.utils.Cycler, other instance in T:\hgwork\site\docs\autodoc\django_site.rst, use :noindex: for one of them
T:\hgwork\site\docs\index.rst:31: WARNING: toctree contains reference to nonexisting document u'about/index'
T:\hgwork\site\docs\releases\index.rst:23: WARNING: toctree glob pattern u'1.0.?' didn't match any documents
T:\hgwork\site\docs\releases\0.0.1.rst:: WARNING: document isn't included in any toctree
<autodoc>:1: WARNING: py:class reference target not found: object
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:1: WARNING: setting reference target not found: SITE
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:3: WARNING: py:mod reference target not found: lino.projects.cosi.Site
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:3: WARNING: setting reference target not found: SITE
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:26: WARNING: setting reference target not found: SITE
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:30: WARNING: setting reference target not found: TEMPLATE_DIRS
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:30: WARNING: setting reference target not found: FIXTURE_DIRS
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site:30: WARNING: setting reference target not found: TEMPLATE_LOADERS
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.django_settings:1: WARNING: py:meth reference target not found: Lino.__init__
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.is_local_project_dir:1: WARNING: py:class reference target not found: Lino
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.loading_from_dump:1: WARNING: py:meth reference target not found: lino.utils.dumpy.Serializer.serialize
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.loading_from_dump:1: WARNING: py:func reference target not found: lino.modlib.cal.models.update_auto_task
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.loading_from_dump:1: WARNING: py:mod reference target not found: lino.modlib.mails.models
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.loading_from_dump:1: WARNING: unknown document: /blog/2011/0901
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.project_dir:11: WARNING: xfile reference target not found: fixtures
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.startup:1: WARNING: py:mod reference target not found: lino.models
t:\hgwork\site\django_site\__init__.py:docstring of django_site.Site.using:6: WARNING: py:meth reference target not found: welcome_html
T:\hgwork\site\docs\autodoc\django_site.rst:8: WARNING: py:class reference target not found: dict
T:\hgwork\site\docs\autodoc\django_site.utils.rst:8: WARNING: py:class reference target not found: dict
